const fmt = require("../ui/format");

const {
  STATUS_INDICATORS,
  StreamBuffer,
  UCODE_BANNER_LINES,
  UCODE_VERSION,
  buildMergedToolExpandedLines,
  buildMergedToolSummaryText,
  buildUcodeBannerLines,
  clampCursorPos,
  createEscapeTagStripper,
  cycleAgentSelectionIndex,
  deleteWordBeforeCursor,
  displayCellWidth,
  filterSelectableAgents,
  findLogicalLineEnd,
  findLogicalLineStart,
  formatPendingElapsed,
  loadActiveAgents,
  moveCursorByWord,
  moveCursorHorizontally,
  moveCursorToVisualLineBoundary,
  moveCursorVertically,
  normalizeBashToolCommand,
  normalizeToolMergeEntry,
  parseActiveAgentsFromBusStatus,
  renderLogLinesWithMarkdown,
  resolveAgentSelectionOnDown,
  resolveHistoryDownTransition,
  shouldClearAgentSelectionOnUp,
  shouldEnterAgentSelection,
  shouldUseUcodeTui,
  stripLeakedEscapeTags,
} = fmt;

function runUcodeTui(props = {}) {
  const { runUcodeInkTui } = require("../ui/components/UcodeApp");
  return runUcodeInkTui(props);
}

module.exports = {
  STATUS_INDICATORS,
  UCODE_BANNER_LINES,
  UCODE_VERSION,
  StreamBuffer,
  displayCellWidth,
  buildUcodeBannerLines,
  parseActiveAgentsFromBusStatus,
  shouldUseUcodeTui,
  renderLogLinesWithMarkdown,
  shouldEnterAgentSelection,
  resolveAgentSelectionOnDown,
  cycleAgentSelectionIndex,
  shouldClearAgentSelectionOnUp,
  moveCursorHorizontally,
  clampCursorPos,
  findLogicalLineStart,
  findLogicalLineEnd,
  moveCursorToVisualLineBoundary,
  moveCursorVertically,
  deleteWordBeforeCursor,
  moveCursorByWord,
  resolveHistoryDownTransition,
  filterSelectableAgents,
  stripLeakedEscapeTags,
  createEscapeTagStripper,
  formatPendingElapsed,
  normalizeBashToolCommand,
  normalizeToolMergeEntry,
  buildMergedToolSummaryText,
  buildMergedToolExpandedLines,
  loadActiveAgents,
  runUcodeTui,
};
