const { applyProjectNicknamePrefix, buildProjectNicknamePrefix, isAutoGeneratedNickname } = require("../../../src/daemon/nicknameScope");

describe("daemon nicknameScope", () => {
  test("builds project prefix from project directory name", () => {
    expect(buildProjectNicknamePrefix("/tmp/My Project")).toBe("my-project");
  });

  test("prefixes explicit nicknames with the project name", () => {
    expect(applyProjectNicknamePrefix("/tmp/ufoo", "architect", { agentType: "claude" })).toBe("ufoo-architect");
    expect(applyProjectNicknamePrefix("/tmp/ufoo", "QA Driver", { agentType: "codex" })).toBe("ufoo-qa-driver");
  });

  test("keeps already-prefixed nicknames idempotent", () => {
    expect(applyProjectNicknamePrefix("/tmp/ufoo", "ufoo-architect", { agentType: "claude" })).toBe("ufoo-architect");
  });

  test("does not prefix provider auto nicknames unless forced", () => {
    expect(isAutoGeneratedNickname("claude-47", "claude")).toBe(true);
    expect(applyProjectNicknamePrefix("/tmp/ufoo", "claude-47", { agentType: "claude" })).toBe("claude-47");
    expect(applyProjectNicknamePrefix("/tmp/ufoo", "claude-47", { agentType: "claude", force: true })).toBe("ufoo-claude-47");
  });
});
