"use strict";

const fs = require("fs");
const path = require("path");
const { getUfooPaths } = require("../../coordination/state/paths");

function asTrimmedString(value) {
  if (typeof value !== "string") return "";
  return value.trim();
}

function normalizeNicknameSegment(value = "", fallback = "agent") {
  const normalized = asTrimmedString(value)
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
  return normalized || fallback;
}

function normalizeAutoNicknamePrefix(agentType = "") {
  const normalized = asTrimmedString(agentType).toLowerCase();
  if (normalized === "claude" || normalized === "claude-code") return "claude";
  if (normalized === "codex") return "codex";
  if (normalized === "ufoo" || normalized === "ucode" || normalized === "ufoo-code") return "ucode";
  return "";
}

function buildProjectNicknamePrefix(projectRoot) {
  const resolvedRoot = asTrimmedString(projectRoot) || process.cwd();
  let baseName = "";
  try {
    const realRoot = fs.realpathSync.native
      ? fs.realpathSync.native(resolvedRoot)
      : fs.realpathSync(resolvedRoot);
    baseName = path.basename(realRoot);
  } catch {
    baseName = path.basename(path.resolve(resolvedRoot));
  }
  return normalizeNicknameSegment(baseName, "project");
}

function isAutoGeneratedNickname(nickname = "", agentType = "") {
  const normalized = normalizeNicknameSegment(nickname, "");
  const match = normalized.match(/^([a-z0-9]+)-([a-z0-9_-]+)$/);
  if (!match) return false;

  const nicknamePrefix = match[1];
  const suffix = match[2];
  const knownPrefixes = new Set(["claude", "codex", "ucode"]);
  const agentPrefix = normalizeAutoNicknamePrefix(agentType);
  if (agentPrefix) knownPrefixes.add(agentPrefix);
  if (!knownPrefixes.has(nicknamePrefix)) return false;
  return /\d/.test(suffix);
}

function applyProjectNicknamePrefix(projectRoot, nickname = "", options = {}) {
  const rawNickname = asTrimmedString(nickname);
  if (!rawNickname) return "";

  const projectPrefix = buildProjectNicknamePrefix(projectRoot);
  const normalizedNickname = normalizeNicknameSegment(rawNickname, "");
  if (!normalizedNickname) return "";

  if (normalizedNickname === projectPrefix || normalizedNickname.startsWith(`${projectPrefix}-`)) {
    return normalizedNickname;
  }

  if (options.force !== true && isAutoGeneratedNickname(normalizedNickname, options.agentType || "")) {
    return normalizedNickname;
  }

  return `${projectPrefix}-${normalizedNickname}`;
}

function stripProjectNicknamePrefix(projectRoot, nickname = "") {
  const normalizedNickname = normalizeNicknameSegment(nickname, "");
  if (!normalizedNickname) return "";
  const projectPrefix = buildProjectNicknamePrefix(projectRoot);
  const scopedPrefix = `${projectPrefix}-`;
  if (!normalizedNickname.startsWith(scopedPrefix)) {
    return normalizedNickname;
  }
  const stripped = normalizedNickname.slice(scopedPrefix.length).replace(/^-+/, "");
  return stripped || normalizedNickname;
}

function resolveDisplayNickname(projectRoot, meta = {}, fallback = "") {
  const explicit = asTrimmedString(meta.nickname);
  const scoped = asTrimmedString(meta.scoped_nickname);
  // Always strip the project prefix off whichever nickname we settle on:
  // group startup (groupOrchestrator) writes the scoped form into both
  // `nickname` and `scoped_nickname`, so the previous "if scoped exists,
  // return nickname as-is" shortcut surfaced the project-prefixed form to
  // the UI instead of the short display name.
  if (explicit) return stripProjectNicknamePrefix(projectRoot, explicit);
  if (scoped) return stripProjectNicknamePrefix(projectRoot, scoped);
  return asTrimmedString(fallback);
}

function resolveScopedNickname(projectRoot, meta = {}, fallback = "") {
  const scoped = asTrimmedString(meta.scoped_nickname);
  if (scoped) return scoped;
  const explicit = asTrimmedString(meta.nickname);
  if (explicit) {
    return meta.scoped_nickname ? scoped : applyProjectNicknamePrefix(projectRoot, explicit, { force: true });
  }
  const fallbackValue = asTrimmedString(fallback);
  if (!fallbackValue) return "";
  return applyProjectNicknamePrefix(projectRoot, fallbackValue, { force: true });
}

function checkAndCleanupNickname(projectRoot, nickname, { tty = "", agentType = "", scopedNickname = "" } = {}) {
  const conflictNickname = scopedNickname || applyProjectNicknamePrefix(projectRoot, nickname, {
    agentType,
    force: true,
  });
  if (!conflictNickname) return { existing: null, cleaned: false };
  const busPath = getUfooPaths(projectRoot).agentsFile;
  try {
    const bus = JSON.parse(fs.readFileSync(busPath, "utf8"));
    const entries = Object.entries(bus.agents || {})
      .filter(([, meta]) => {
        const candidate = resolveScopedNickname(projectRoot, meta);
        return meta && candidate === conflictNickname;
      });

    if (entries.length === 0) {
      return { existing: null, cleaned: false };
    }

    const activeAgent = entries.find(([, meta]) => meta.status === "active");
    if (activeAgent) {
      const [existingId, existingMeta] = activeAgent;
      const sameType = agentType && existingMeta.agent_type === agentType;
      const isStub = sameType && !existingMeta.tty && !existingMeta.activity_state;
      const sameTty = tty && existingMeta.tty === tty;
      if (isStub || sameTty) {
        delete bus.agents[existingId];
        fs.writeFileSync(busPath, JSON.stringify(bus, null, 2));
        return { existing: null, cleaned: true };
      }
      return { existing: existingId, cleaned: false };
    }

    for (const [agentId] of entries) {
      delete bus.agents[agentId];
    }
    fs.writeFileSync(busPath, JSON.stringify(bus, null, 2));
    return { existing: null, cleaned: true };
  } catch {
    return { existing: null, cleaned: false };
  }
}

module.exports = {
  normalizeNicknameSegment,
  buildProjectNicknamePrefix,
  isAutoGeneratedNickname,
  applyProjectNicknamePrefix,
  stripProjectNicknamePrefix,
  resolveDisplayNickname,
  resolveScopedNickname,
  checkAndCleanupNickname,
};
