"use strict";

const fs = require("fs");
const path = require("path");

function asTrimmedString(value) {
  if (typeof value !== "string") return "";
  return value.trim();
}

function normalizeNicknameSegment(value = "", fallback = "agent") {
  const normalized = asTrimmedString(value)
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
  return normalized || fallback;
}

function normalizeAutoNicknamePrefix(agentType = "") {
  const normalized = asTrimmedString(agentType).toLowerCase();
  if (normalized === "claude" || normalized === "claude-code") return "claude";
  if (normalized === "codex") return "codex";
  if (normalized === "ufoo" || normalized === "ucode" || normalized === "ufoo-code") return "ucode";
  return "";
}

function buildProjectNicknamePrefix(projectRoot) {
  const resolvedRoot = asTrimmedString(projectRoot) || process.cwd();
  let baseName = "";
  try {
    const realRoot = fs.realpathSync.native
      ? fs.realpathSync.native(resolvedRoot)
      : fs.realpathSync(resolvedRoot);
    baseName = path.basename(realRoot);
  } catch {
    baseName = path.basename(path.resolve(resolvedRoot));
  }
  return normalizeNicknameSegment(baseName, "project");
}

function isAutoGeneratedNickname(nickname = "", agentType = "") {
  const normalized = normalizeNicknameSegment(nickname, "");
  const match = normalized.match(/^([a-z0-9]+)-([a-z0-9_-]+)$/);
  if (!match) return false;

  const nicknamePrefix = match[1];
  const suffix = match[2];
  const knownPrefixes = new Set(["claude", "codex", "ucode"]);
  const agentPrefix = normalizeAutoNicknamePrefix(agentType);
  if (agentPrefix) knownPrefixes.add(agentPrefix);
  if (!knownPrefixes.has(nicknamePrefix)) return false;
  return /\d/.test(suffix);
}

function applyProjectNicknamePrefix(projectRoot, nickname = "", options = {}) {
  const rawNickname = asTrimmedString(nickname);
  if (!rawNickname) return "";

  const projectPrefix = buildProjectNicknamePrefix(projectRoot);
  const normalizedNickname = normalizeNicknameSegment(rawNickname, "");
  if (!normalizedNickname) return "";

  if (normalizedNickname === projectPrefix || normalizedNickname.startsWith(`${projectPrefix}-`)) {
    return normalizedNickname;
  }

  if (options.force !== true && isAutoGeneratedNickname(normalizedNickname, options.agentType || "")) {
    return normalizedNickname;
  }

  return `${projectPrefix}-${normalizedNickname}`;
}

module.exports = {
  normalizeNicknameSegment,
  buildProjectNicknamePrefix,
  isAutoGeneratedNickname,
  applyProjectNicknamePrefix,
};
